version: '3'

services:
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: northwind
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./data/northwind.sql:/docker-entrypoint-init-db.d/northwind.sql
      - ./data/order_details.csv:/var/order_details.csv
    ports:
      - 5432:5432